[package]
name = "json-parser-test"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simd-json = { version = "0.15", optional = true }

[features]
default = []
simd = ["simd-json"]
